config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  get 'welcome/about', as: "about"
  get 'welcome/contact', as: "contact"

  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }, controllers: { registrations: "registrations"}

  resources :users, only: :show do
    resources :maps, shallow: true
  end
  resources :contact_messages, only: :create
  authenticated do
    root 'users#show'
  end

  root 'welcome#index', as: "guest_root"
end

app/models/contact_message.rb
class ContactMessage
  include ActiveAttr::Model
  attribute :email
  attribute :name
  attribute :subject
  attribute :content
  attribute :dummy

  validates :name, :email, :subject, :content, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :content, length: { maximum: 500 }

  def initialize(attributes={})
    attributes.each do |key, value|
      send("#{ key }=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/edge.rb
class Edge < ActiveRecord::Base
  belongs_to :map
  belongs_to :source, class_name: "Point"
  belongs_to :target, class_name: "Point"

  validate :uniqueness_of_source_and_target
  validates :source_id, :target_id, presence: true

  def uniqueness_of_source_and_target
    self.errors.add :source, "Cannot be the same as target" if source == target
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user

  has_many :points
  has_many :edges

  validates :name, presence: true

  def simplified_edges
    point_list = points.pluck(:id).sort
    edges.select(:source_id, :target_id).reduce([]) { |r, edge| r << [point_list.index(edge.source_id), point_list.index(edge.target_id) ] }
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :map
  has_many :edges, as: :source, foreign_key: :source_id
  has_many :edges, as: :target, foreign_key: :target_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :maps

  def to_s
    nickname || email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  def new
    @contact_message = ContactMessage.new
  end

  def create
    @contact_message = ContactMessage.new(params[:contact_message])
    if @contact_message.valid?
      ContactMailer.contact_message(@contact_message).deliver_now!
      flash.now[:notice] = I18n.t("notifications.notices.contact_messages.sent")
      @contact_message = ContactMessage.new
    else
      flash.now[:alert] = I18n.t("notifications.alerts.contact_messages.invalid")
    end

    flash_message = render_to_string partial: "shared/flash"
    form = render_to_string partial: "shared/contact_form"
    render json: { form: form, flash: flash_message }
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  def index
    @maps = Map.all
  end

  def show
  end

  def new
    @map = Map.new
  end

  def edit
  end

  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params

  protected

    def configure_account_update_params
      devise_parameter_sanitizer.for(:account_update) << [:nickname, :organization]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = params[:id].present? ? User.find(params[:id]) : current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :organization)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
    @contact_message = ContactMessage.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_main_nav.slim
ul.nav class== additional_class
  li = link_to t(".about"), about_path
  li = link_to t(".contact"), contact_path
  - if current_user
    li = link_to t(".logout"), destroy_user_session_path, method: :delete
  - else
    li = link_to t(".sign_in"), new_user_session_path
    li = link_to t(".sign_up"), new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Source"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        / this is visible only on small screen
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        
        = link_to image_tag("small.png", height: '32') , root_url, class: "navbar-brand"
          
        .navbar-collapse.collapse.navbar-responsive-collapse
          = render "layouts/main_nav", additional_class: "navbar-nav"
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          / .well.sidebar-nav
          /   h3 Sidebar
          /   = render "layouts/main_nav", additional_class: "nav-list"

      footer.navbar-fixed-bottom
        div.container
          h5 &copy; Sebastian Wilgosz & Radosław Skiba

app/views/maps/_form.html.slim
= simple_form_for(@map) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user

  .form-actions
    = f.button :submit

app/views/maps/_map.slim
li
  span.name = link_to map.name, map
  span.user = " made by #{map.user}"

app/views/maps/edit.html.slim
h1 Editing map

== render 'form'

= link_to 'Show', @map
'|
= link_to 'Back', @map.user

app/views/maps/index.html.slim
h1 Listing maps

ul
  = render @maps

app/views/maps/new.html.slim
h1 New map

== render 'form'

= link_to 'Back', maps_path

app/views/maps/show.html.slim
p#notice = notice

#map-wrapper data-id==@map.id
  .header
    h3 = @map.name
    p
      strong Made by:
      = " #{ @map.user }"

  .content

  .footer
  = link_to 'Edit', edit_map_path(@map)
  '|
  / = link_to 'Back', maps_path

app/views/shared/_contact_form.slim
= simple_form_for @contact_message, remote: true do |f|
  .form-group
    = f.input :name, placeholder: t(".full_name"), label: false, input_html: { class: "form-control"}
  .form-group
    = f.input :email, placeholder: t(".email_address"), label: false, input_html: { class: "form-control"}
  .form-group
    = f.input :subject, placeholder: t(".subject"), label: false, input_html: { class: "form-control"}
  .row
    .col-md-10
      .form-group
        = f.input :content, as: :text, placeholder: t(".message"), label: false, input_html: { class: "form-control"}, rows: 10
    .col-md-2.nopadl
      .form-actions
        = f.button :submit, value: t(".submit"), class: "btn btn-lg pull-center contact-btn"
/ End Form Contact
.result

app/views/shared/_flash.slim
- if alert
  .alert.alert-danger.alert-dismissible role="alert"
    button.close type="button" data-dismiss="alert"
      span aria-hidden="true" &times;
      span.sr-only Close
    = alert

- if notice
  .alert.alert-success.alert-dismissible role="alert"
    button.close type="button" data-dismiss="alert"
      span aria-hidden="true" &times;
      span.sr-only Close
    = notice

app/views/users/show.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:nickname) + ':'
  br
  = @user.nickname
p
  strong= model_class.human_attribute_name(:organization) + ':'
  br
  = @user.organization
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email


= render @user.maps

br

= link_to t('.edit'), edit_user_registration_path, :class => 'btn btn-primary'
'
= link_to t('.destroy'), user_registration_path, method: :delete, :data => { confirm: "Are you sure?" }, :class => 'btn btn-danger'

app/views/welcome/about.html.slim
h1 Pora pobrudzić sobie trochę ręce !
p Na szczęście z naszą aplikacją wcale nie będziesz musiał...

br

p 
	
	h3 Gdzie ja trafiłem ?
	h3
		small Jesteś na stronie projektu Avalanche, aplikacji ,która w przyszłości pomoże luziom przenosić  
		      swoje pomysły w łatwiejszy sposób do rzeczywistości.
	
	h3 Co mogę aktualnie zrobić ?
	h3
		small Aktualnie jeszcze nic , jednak ciągle pracujemy nad tym byś mógł za niedługo skorzystać 
			  z naszego edytora 3D.

	h3 Co będę mógł zrobić ?
	h3
		small Za niedługo będziesz mógł utworzyć abstrakcyjną mapkę, która świetnie będzie nadawać się
			 do Twojej prezentacji.
	h3 Co najpierw ?
	h3
		small Polecam założyć konto da Ci ono dostęp do swojego panelu mapek, i pomoże zarządzać swoimi pracami.

app/views/welcome/contact.html.slim
/ Contact Us
section#contact
  .container
    .row.margint20.marginb40
      h1.page-title.marginb20 = t(".title")
      hr.tall
      .col-md-8.center
        = render "shared/flash"
        = render "shared/contact_form"

app/views/welcome/index.html.slim
div.row
	.col-md-offset-6
		h1.text-center 
			span.glyphicon.glyphicon-ok
div.row
	.col-md-offset-6
		p.text-center
			i
				cite "Lo­gika zap­ro­wadzi cię z pun­ku A do pun­ktu B. Wyob­raźnia zap­ro­wadzi cię wszędzie." - A.Einstein 
		
	

		br

		h4.text-center Jeden obraz wystarcza za 1000 słów i taki będzie Avalanche. Stworzysz to czego nie będziesz w stanie wyrazić myślami. Pokażesz nie tylko to co potrzebujesz, ale takze to co warto. Wszystko to zgromadzisz w chmurze. 